# Generated by Django 5.1.2 on 2024-10-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_post_shared_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='uploads/profile_audios'),
        ),
    ]
